## Pandas

- A package built on top of NumPy
- Two core objects in Pandas: DataFrame & the Series

In [2]:
# DataFrame - a two-dimensional, size-mutable, tabular data structure with labeled axes (rows and columns)
# Basically like an excel table, but in Python
import pandas as pd

print("Example 1:")
display(pd.DataFrame({"Yes": [50, 21], "No": [131, 2]}))

print("Example 2:")
df = pd.DataFrame({
    "height": [170, 180, 175],
    "weight": [65, 80, 70]
})

display(df)

Example 1:

   Yes   No
0   50  131
1   21    2

Example 2:

   height  weight
0     170      65
1     180      80
2     175      70

In [3]:
# Change labels
pd.DataFrame({"Bob": ["I liked it.", "It was awful."], 
              "Sue": ["Pretty good.", "Bland."]},
             index=["Product A", "Product B"])

                     Bob           Sue
Product A    I liked it.  Pretty good.
Product B  It was awful.        Bland.

In [4]:
# Series - is a sequence of data values; a single column of a DataFrame
# It is a one-dimensional labeled array capable of holding any data type 

display(pd.Series([1, 2, 3, 4, 5]))

# Assign row labels
display(pd.Series([30, 35, 40], index=['2015 Sales', '2016 Sales', '2017 Sales'], name='Product A'))

# You can think of DataFrame as a bunch of Series glued together.

0    1
1    2
2    3
3    4
4    5
dtype: int64

2015 Sales    30
2016 Sales    35
2017 Sales    40
Name: Product A, dtype: int64

In [5]:
# Reading data files

# df = pd.read_csv("my_data.csv")
# pd.read_csv("my_data.csv", nrows=5) - read only first 5 rows of the csv file
# Has many other parameters to customize how the csv file is read, such as specifying the delimiter, handling missing values, etc.
    # index_col, index_row, header, names, skiprows, na_values, dtype, parse_dates, etc. 

data = pd.DataFrame({
    "height": [170, 180, 175],
    "weight": [65, 80, 70],
    "hair_color": ["black", "brown", "blonde"],
    "is_married": [False, True, False],
    "children": [0, 2, 1],
    "hobbies": [["reading", "hiking"], ["cooking", "traveling"], ["painting"]],
    "age": [30, 40, 35],
    "income": [50000, 80000, 60000]
})

print(data.shape) # (3, 6) - 3 rows, 6 columns

display(data.head(3)) # first 3 rows
display(data.tail(3)) # last 3 rows

(3, 8)

,height,weight,hair_color,is_married,children,hobbies,age,income
0,170,65,black,False,0,"[reading, hiking]",30,50000
1,180,80,brown,True,2,"[cooking, traveling]",40,80000
2,175,70,blonde,False,1,[painting],35,60000

,height,weight,hair_color,is_married,children,hobbies,age,income
0,170,65,black,False,0,"[reading, hiking]",30,50000
1,180,80,brown,True,2,"[cooking, traveling]",40,80000
2,175,70,blonde,False,1,[painting],35,60000

In [6]:
# Native Accessors
# .str - for string operations
# .dt - for datetime operations
# .cat - for categorical data operations
# .plot - for plotting data
# These accessors allow you to perform vectorized operations on the data in a Series or DataFrame column, making it easier to manipulate and analyze the data.

reviews = pd.DataFrame({"Country": ["Italy", "Italy", "France", "France", "Spain"],
                        "Venue Name": ["Cafe A", "Cafe B", "Cafe C", "Cafe D", "Cafe E"],
                        "Review": ["Great coffee!", "Not bad.", "Loved it!", "Could be better.", "Fantastic!"]})

display(reviews)

print(reviews.Country) # Attribute access 
print(reviews["Country"]) # Dictionary-style access 

print(reviews["Country"][0]) # Accessing the first element of the "Country" column

  Country Venue Name            Review
0   Italy     Cafe A     Great coffee!
1   Italy     Cafe B          Not bad.
2  France     Cafe C         Loved it!
3  France     Cafe D  Could be better.
4   Spain     Cafe E        Fantastic!

0     Italy
1     Italy
2    France
3    France
4     Spain
Name: Country, dtype: object
0     Italy
1     Italy
2    France
3    France
4     Spain
Name: Country, dtype: object
Italy

In [7]:
# Indexing in Pandas
# Has two paradigms: Index-based and label-based indexing
    # Both are row-first, column-second

# Index-based: selecting data based on its numerical position in the data:
print(reviews.iloc[0]) # Access the first row of the DataFrame

# Retrieve Columns
print("\n", reviews.iloc[:, 0]) # Access the "Country" column using integer-location based indexing
# or print(reviews["Country"])

# Can also pass list reviews.iloc[[0, 1, 2], 0] to get the first 3 rows of the "Country" column

Country               Italy
Venue Name           Cafe A
Review        Great coffee!
Name: 0, dtype: object

 0     Italy
1     Italy
2    France
3    France
4     Spain
Name: Country, dtype: object

In [8]:
# Label-based: selecting data based on the data index value, not its position 

print(reviews.loc[0, "Country"]) 

print("\n", reviews.loc[0]) # Access the first row of the DataFrame using label-based indexing (if the index is labeled with integers, this will give the same result as iloc[0])

Italy

 Country               Italy
Venue Name           Cafe A
Review        Great coffee!
Name: 0, dtype: object

In [ ]:
# - iloc is used for integer-based indexing, where you select data based on its position
# - loc is used for label-based indexing, where you select data based on the index labels
# both are row-first, column-second

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

Name       Alice
Age           25
City    New York
Name: 0, dtype: object
Bob
Name       Alice
Age           25
City    New York
Name: 0, dtype: object

In [20]:
# Manipulating the index (from Kaggle lesson - so use that)
# reviews.set_index("Venue Name", inplace=True) # this will change the index of the DataFrame to the "Venue Name" column, and the original index will be lost.
# display(reviews)

# Conditional Selection, explain quickly with example 
display(reviews[reviews["Country"] == "Italy"]) # this will return a new DataFrame containing only the rows where the "Country" column is equal to "Italy"

# isin - to filter rows based on whether a column's values are in a list of values
display(reviews[reviews["Country"].isin(["Italy", "France"])]) # this will return a new DataFrame containing only the rows where the "Country" column is either "Italy" or "France"

           Country         Review
Venue Name
Cafe A       Italy  Great coffee!
Cafe B       Italy       Not bad.

           Country            Review
Venue Name
Cafe A       Italy     Great coffee!
Cafe B       Italy          Not bad.
Cafe C      France         Loved it!
Cafe D      France  Could be better.

In [22]:
# isnull - to filter rows based on whether a column's values are null (missing)
display(reviews[reviews["Country"].isnull()]) # this will return a new DataFrame containing only the rows where the "Country" column has null (missing) values

# notnull - to filter rows based on whether a column's values are not null (not missing)
display(reviews[reviews["Country"].notnull()]) # this will return a new DataFrame containing only the rows where the "Country" column has non-null (not missing) values

Empty DataFrame
Columns: [Country, Review]
Index: []

           Country            Review
Venue Name
Cafe A       Italy     Great coffee!
Cafe B       Italy          Not bad.
Cafe C      France         Loved it!
Cafe D      France  Could be better.
Cafe E       Spain        Fantastic!

In [39]:
# Assigning data to a DataFrame (existing data or new data)  
reviews["Num_of_tables"] = [5,6,9,11,16]  # this will create a new column named "New_Column" and assign the specified values to it

reviews["visit_closeby"] = ["Tower of Pisa", "Pisa Museum", "Eiffel Tower", "Eiffel flower shop", "Madrid Statue"]

display(reviews)

,Country,Review,New_Column,visit_closeby,Num_of_tables
Venue Name,,,,,
Cafe A,Italy,Great coffee!,5,Tower of Pisa,5
Cafe B,Italy,Not bad.,6,Pisa Museum,6
Cafe C,France,Loved it!,9,Eiffel Tower,9
Cafe D,France,Could be better.,11,Eiffel flower shop,11
Cafe E,Spain,Fantastic!,16,Madrid Statue,16

In [40]:
# Summary Functions
print(reviews.Num_of_tables.describe()) # describe() generates a high-level summary of the attributes of the given column

# describe is type aware, this is what you get for string data:
print("\n", reviews.visit_closeby.describe())

# You can also get simple summary statistics
reviews.Num_of_tables.mean()

# .unique() to see unique values
# .value_counts() to see a list of unique values AND how often they occur in the dataset

count     5.000000
mean      9.400000
std       4.393177
min       5.000000
25%       6.000000
50%       9.000000
75%      11.000000
max      16.000000
Name: Num_of_tables, dtype: float64

 count                 5
unique                5
top       Tower of Pisa
freq                  1
Name: visit_closeby, dtype: object

9.4

In [ ]:
# Map - a function that takes one set of values and "maps" them to another set of values
Num_of_tables_mean = reviews.Num_of_tables.mean()
reviews.Num_of_tables.map(lambda p: p - Num_of_tables_mean) # subtract each value in Num_of_tables by mean 
# map returns a new Series where all the values have been transformed by the function

# apply() is the equivalent method to transform a whole DataFrame by calling a custom method on each row.
# returns new DataFrame

# Neither modies the original data they're called on 
# faster way to map: (reviews.Num_of_tables - Num_of_tables_mean)

Venue Name
Cafe A   -4.4
Cafe B   -3.4
Cafe C   -0.4
Cafe D    1.6
Cafe E    6.6
Name: Num_of_tables, dtype: float64

In [10]:
# Filtering Rows
df[df["height"] > 175]

# Creating New Columns
df["bmi"] = df["weight"] / (df["height"]/100)**2