## Pandas

- A package built on top of NumPy
- Two core objects in Pandas: DataFrame & the Series

In [ ]:
# DataFrame - a two-dimensional, size-mutable, tabular data structure with labeled axes (rows and columns)
# Basically like an excel table, but in Python
import pandas as pd

print("Example 1:")
display(pd.DataFrame({"Yes": [50, 21], "No": [131, 2]}))

print("Example 2:")
df = pd.DataFrame({
    "height": [170, 180, 175],
    "weight": [65, 80, 70]
})

display(df)

Example 1:

   Yes   No
0   50  131
1   21    2

Example 2:

   height  weight
0     170      65
1     180      80
2     175      70

In [3]:
# Change labels
pd.DataFrame({"Bob": ["I liked it.", "It was awful."], 
              "Sue": ["Pretty good.", "Bland."]},
             index=["Product A", "Product B"])

                     Bob           Sue
Product A    I liked it.  Pretty good.
Product B  It was awful.        Bland.

In [9]:
# Series - is a sequence of data values; a single column of a DataFrame
# It is a one-dimensional labeled array capable of holding any data type 

display(pd.Series([1, 2, 3, 4, 5]))

# Assign row labels
display(pd.Series([30, 35, 40], index=['2015 Sales', '2016 Sales', '2017 Sales'], name='Product A'))

# You can think of DataFrame as a bunch of Series glued together.

0    1
1    2
2    3
3    4
4    5
dtype: int64

2015 Sales    30
2016 Sales    35
2017 Sales    40
Name: Product A, dtype: int64

In [ ]:
# Reading data files

# df = pd.read_csv("my_data.csv")
# pd.read_csv("my_data.csv", nrows=5) - read only first 5 rows of the csv file
# Has many other parameters to customize how the csv file is read, such as specifying the delimiter, handling missing values, etc.
    # index_col, index_row, header, names, skiprows, na_values, dtype, parse_dates, etc. 

data = pd.DataFrame({
    "height": [170, 180, 175],
    "weight": [65, 80, 70],
    "hair_color": ["black", "brown", "blonde"],
    "is_married": [False, True, False],
    "children": [0, 2, 1],
    "hobbies": [["reading", "hiking"], ["cooking", "traveling"], ["painting"]],
    "age": [30, 40, 35],
    "income": [50000, 80000, 60000]
})

print(data.shape) # (3, 6) - 3 rows, 6 columns

display(data.head(3)) # first 3 rows
display(data.tail(3)) # last 3 rows

(3, 8)

,height,weight,hair_color,is_married,children,hobbies,age,income
0,170,65,black,False,0,"[reading, hiking]",30,50000
1,180,80,brown,True,2,"[cooking, traveling]",40,80000
2,175,70,blonde,False,1,[painting],35,60000

,height,weight,hair_color,is_married,children,hobbies,age,income
0,170,65,black,False,0,"[reading, hiking]",30,50000
1,180,80,brown,True,2,"[cooking, traveling]",40,80000
2,175,70,blonde,False,1,[painting],35,60000

In [4]:
# Accessing Data
print("This is the head of the dataframe \n", df.head()) # Gives first few rows of beginning of dataframe
print("\n This is the tail of the dataframe \n", df.tail())
print("\n")
print(df["height"])
print(df.loc[0])
print(df.loc[0, "height"])

This is the head of the dataframe
    height  weight
0     170      65
1     180      80
2     175      70

 This is the tail of the dataframe
    height  weight
0     170      65
1     180      80
2     175      70


0    170
1    180
2    175
Name: height, dtype: int64
height    170
weight     65
Name: 0, dtype: int64
170

In [14]:
# Filtering Rows
df[df["height"] > 175]

# Creating New Columns
df["bmi"] = df["weight"] / (df["height"]/100)**2